language: java

jdk:
  - oraclejdk8
  
jobs:
  - name: JustAnotherTest_runSH      # required
    type: runSH             # required
    steps:                  # required
      - IN: nightly
      - IN: testRepo
      - Task:
        - script: cd /mvn-parent
        - script: mvn clean verify surefire:test
    on success: 
        - script: echo "SUCCESS"
    on failure:
        - script: echo "FAILURE"
    on cancel:
        - script: echo "CANCEL"
    always:
        - script: echo pwd