language: java

jdk:
  - oraclejdk8
  
jobs:
  - name: JustAnotherTest_runCI      # required
    type: runCI             # required
    steps:                  # required
      - IN: nightly
      - IN: testRepo