language: java

jdk:
  - oraclejdk8

matrix:
    - BRANCH="master"
    - BRANCH="testbranch"
  
jobs:
  - name: JustAnotherTest_runCI      # required
    type: runCI             # required
    steps:                  # required
      - IN: nightly