language: java

jdk:
  - oraclejdk8
  
jobs:
  - name: TestStuff_runCI      # required
    type: runCI             # required
    steps:                  # required
      - IN: nightly-trigger
      - IN: testRepo